### ISSUE TITLE
Idea about angular module namespace & autocompletion

### ISSUE THREAD

**Issue by raDiesle** [basarat/video-angular-typescript#2]
Hi,

in your example, angularjs names are string based,
so at runtime you'll realize, that something is wrong.

I see using transformations in grunt-ts for index.ts files, which is a killer feature.

Wouldn't it be cool, to generate some namespace related to the folder path,
so that you can later on reference?

e.g. 

angular.module(APP_SERVICES, []). factory(APP_SERVICES_DATASERVICE, dataServiceSingleton);

or probably easier:

withing every file, generate an additional export of file-name

**Comment by basarat** [comment]
There is a lot of `magic string` based work in AngularJS. The worst is the HTML. If someone has 6 months off, and they integrate AngularJS + Typescript/TypeSafety in the templates they will make a great career jump. 

The _names of the files_ is not a place where most bugs are unfortunately (as these get caught quickly since we get a "svc or svcProvider not found" etc error from Angular's Dependency Injection), so I don't see a massive gain here.

But I am investigating _other areas_ of improvement. More into Node.js / CommonJS workflow simplification right now.
